Applicant Details

SELECT 
    ID,
    NAME,
    SURNAME,
    ID_NUMBER,
    TRUNC(MONTHS_BETWEEN(SYSDATE,DOB)/12) AS AGE,
    FILE_NUMBER,
    DATE_INTAKE,
    CELL_NUMBER,
    ALTERNATE_NUMBER,
    EMAIL_ADDRESS,
    STREET_ADDRESS,
    POPIA,
    RACE_ID,
    NATIONALITY_ID,
    GENDER_ID,
    FILE_CONDITION_ID,
    FILE_STATUS_ID,
    HIGHEST_EDUCATION_ID,
    MARITUAL_STATUS_ID,
    EMPLOYMENT_STATUS_ID,
    SUBURB_ID,
    DWELLING_TYPE_ID,
    DWELLING_STATUS_ID,
    HEALTH_ID,
    SKILLS_ID,
    CREATED_BY,
    DATESTAMP
FROM WELFARE_APPLICANT_DETAILS;

Total Financial Assistance

SELECT 
    WA.NAME,
    WA.SURNAME,
    WA.FILE_NUMBER,
    WA.FILE_CONDITION_ID,
    WA.FILE_STATUS_ID,
    WA.EMPLOYMENT_STATUS_ID,
    WA.HEALTH_ID,
    WA.CELL_NUMBER,
    COALESCE(SUM(FA.FINANCIAL_COST), 0) AS FINANCIAL_FOOD_ASSISTANCE,
    COALESCE(SUM(AT.FINANCIAL_AMOUNT), 0) AS FINANCIAL_TRANSACTIONS,
    COALESCE(SUM(FA.FINANCIAL_COST), 0) + COALESCE(SUM(AT.FINANCIAL_AMOUNT), 0) AS TOTAL_FINANCIAL
FROM 
    WELFARE_APPLICANT_DETAILS WA
LEFT JOIN 
    APPLICANT_FOOD_ASSISTANCE FA ON FA.WELFARE_APPLICANT_DETAIL_ID = WA.ID
LEFT JOIN 
    APPLICANT_TRANSACTIONS AT ON AT.WELFARE_APPLICANT_DETAIL_ID = WA.ID
GROUP BY
    WA.NAME,
    WA.SURNAME,
    WA.FILE_NUMBER,
    WA.CELL_NUMBER,
    WA.FILE_CONDITION_ID,
    WA.FILE_STATUS_ID,
    WA.EMPLOYMENT_STATUS_ID,
    WA.HEALTH_ID;

Financial Assistance
SELECT 
    WA.NAME,
    WA.SURNAME,
    WA.FILE_NUMBER,
    WA.CELL_NUMBER,

    AT.ASSISTED_BY,
    AT.FINANCIAL_AMOUNT,
    AT.ASSISTANCE_TYPE_ID,
    AT.DATE_OF_ASSITANCE,
    AT.CREATED_BY,
    AT.DATESTAMP
FROM 
            APPLICANT_TRANSACTIONS AT
INNER JOIN 
    WELFARE_APPLICANT_DETAILS WA ON AT.WELFARE_APPLICANT_DETAIL_ID = WA.ID;

Food Assistance
SELECT 
    WA.NAME,
    WA.SURNAME,
    WA.FILE_NUMBER,
    WA.CELL_NUMBER,

    FA.HAMPER_TYPE,
    FA.FINANCIAL_COST,
    FA.ASSISTED_BY,
    FA.DISTRIBUTED_DATE,
    FA.CREATED_BY,
    FA.DATESTAMP
FROM 
            APPLICANT_FOOD_ASSISTANCE FA
INNER JOIN 
    WELFARE_APPLICANT_DETAILS WA ON FA.WELFARE_APPLICANT_DETAIL_ID = WA.ID;

Home Visits
SELECT 
    WA.NAME,
    WA.SURNAME,
    WA.FILE_NUMBER,
    WA.CELL_NUMBER,

    HV.VISIT,
    HV.REPRESENTATIVE,
    HV.THE_COMMENT,
    HV.ATTACHMENT_1,
    HV.ATTACHMENT_2,
    HV.CREATED_BY,
    HV.DATESTAMP
FROM 
            APPLICANT_HOME_VISITS HV
INNER JOIN 
    WELFARE_APPLICANT_DETAILS WA ON HV.WELFARE_APPLICANT_DETAIL_ID = WA.ID;

Relationship Report
SELECT 
    WA.NAME,
    WA.SURNAME,
    WA.FILE_NUMBER,
    WA.CELL_NUMBER,

    WR.RELATIONSHIP_TYPE_ID,
    WR.NAME as Relatives_Name,
    WR.SURNAME as Relatives_Surname ,
    WR.EMPLOYMENT_STATUS,
    WR.GENDER,
    TRUNC(MONTHS_BETWEEN(SYSDATE, WR.DOB)/12) AS AGE,
    WR.HIGHEST_EDUCATION,
    WR.Marital_STATUS,
    WR.HEALTH_CONDITION
FROM 
            APPLICANT_RELATIONSHIP WR
INNER JOIN 
    WELFARE_APPLICANT_DETAILS WA ON WR.WELFARE_APPLICANT_DETAIL_ID = WA.ID;


Applicant Programs
SELECT 
    WA.NAME,
    WA.SURNAME,
    WA.FILE_NUMBER,
    WA.CELL_NUMBER,

    AP.PROGRAM_NAME_ID,
    AP.DATE_OF_PROGRAM,
    AP.MEANS_OF_COMMUNICATIONS_ID,
    AP.ATTENDANCE_STATUS,
    AP.WHO_COMMUNICATED,
    AP.CREATED_BY,
    AP.DATESTAMP
FROM 
            APPLICANT_PROGRAMS AP
INNER JOIN 
    WELFARE_APPLICANT_DETAILS WA ON AP.WELFARE_APPLICANT_DETAIL_ID = WA.ID;